# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "gateway", autostart: true do |gateway|
    gateway.vm.box = "ubuntu/trusty64"
    # gateway.vm.box_url = "/courses/webspace/cscd27f16/assignment/02/boxes/ubuntu-trusty64_virtualbox.box"
    gateway.vm.network "private_network", ip: "10.0.1.100"
    gateway.vm.hostname = "gateway"
    gateway.vm.provision "shell", path: "gateway/setup.sh"
    gateway.vm.provider 'virtualbox' do |v|
      v.customize ["modifyhd", "disk id", "--resize", "1024"]
    end
  end

  config.vm.define "alice", autostart: true do |alice|
    alice.vm.box = "ubuntu/trusty64"
    # alice.vm.box_url = "/courses/webspace/cscd27f16/assignment/02/boxes/ubuntu-trusty64_virtualbox.box"
    alice.vm.network "private_network", ip: "10.0.1.101"
    alice.vm.hostname = "alice"
    alice.vm.provision "shell", path: "alice/setup.sh"
    alice.vm.provision "shell", run: "always", inline: "sudo route add default gw 10.0.1.100"
    alice.vm.provider 'virtualbox' do |v|
      v.customize ["modifyhd", "disk id", "--resize", "1024"]
    end
  end

  config.vm.define "mallory", autostart: true do |mallory|
    mallory.vm.box = "ubuntu/trusty64"
    # mallory.vm.box_url = "/courses/webspace/cscd27f16/assignment/02/boxes/ubuntu-trusty64_virtualbox.box"
    mallory.vm.network "private_network", ip: "10.0.1.102"
    mallory.vm.hostname = "mallory"
    mallory.vm.network "forwarded_port", guest: 8080, host: 8080
    mallory.vm.provision "shell", path: "mallory/setup.sh"
    mallory.ssh.forward_x11 = true
    mallory.vm.provider 'virtualbox' do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end

end
