# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "minimal/trusty64"
  config.vm.box_url = "http://mathlab.utsc.utoronto.ca/courses/cscd27f16/assignment/02/boxes/trusty64_minimal.box"

  config.vm.define "gateway", autostart: true do |gateway|
    gateway.vm.network "private_network", ip: "10.0.1.100"
    gateway.vm.hostname = "gateway"
    gateway.vm.provision "shell", path: "gateway/setup.sh"
    gateway.vm.provision "shell", run: "always", inline: "service iptables-persistent start"
    gateway.vm.provider 'virtualbox' do |v|
      v.customize ["modifyvm", :id, "--audio", "none", "--usb", "on", "--usbehci", "off"]
      unless File.exist?("gateway.vdi")
        v.customize ["createhd",  "--filename", "gateway.vdi", "--size", "2048"]
        v.customize [ "storageattach", :id, "--storagectl", "SATA", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "gateway.vdi" ]
      end
    end
  end

  config.vm.define "alice", autostart: true do |alice|
    alice.vm.network "private_network", ip: "10.0.1.101"
    alice.vm.hostname = "alice"
    alice.vm.provision "shell", path: "alice/setup.sh"
    alice.vm.provision "shell", run: "always", inline: "sudo route add default gw 10.0.1.100"
    alice.vm.provider 'virtualbox' do |v|
      v.customize ["modifyvm", :id, "--audio", "none", "--usb", "on", "--usbehci", "off"]
      unless File.exist?("alice.vdi")
        v.customize ["createhd",  "--filename", "alice.vdi", "--size", "2048"]
        v.customize [ "storageattach", :id, "--storagectl", "SATA", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "alice.vdi" ]
      end
    end
  end

  config.vm.define "mallory", autostart: true do |mallory|
    mallory.vm.network "private_network", ip: "10.0.1.102"
    mallory.vm.hostname = "mallory"
    mallory.vm.provision "shell", path: "mallory/setup.sh"
    mallory.ssh.forward_x11 = true
    mallory.vm.provider 'virtualbox' do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.customize ["modifyvm", :id, "--audio", "none", "--usb", "on", "--usbehci", "off"]
      unless File.exist?("mallory.vdi")
        v.customize ["createhd",  "--filename", "mallory.vdi", "--size", "2048"]
        v.customize [ "storageattach", :id, "--storagectl", "SATA", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "mallory.vdi" ]
      end
      # v.gui = true
      # v.memory = "1024"
    end
  end

end
