# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

   config.vm.define "target", autostart: true do |target|
     target.vm.box = "daniele2010/Metasploitable2"
     target.vm.network "private_network", ip: "10.0.1.101"
   end

   config.vm.define "kali", autostart: true do |kali|
     kali.vm.box = "blackfin/kali"
     kali.vm.network "private_network", ip: "10.0.1.102"
     kali.vm.network "forwarded_port", guest: 9392, host: 9392
     kali.vm.hostname = "kali"
     kali.ssh.username = "root"
     kali.ssh.password = "toor"
   end

end