# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "minimal/trusty64"
  config.vm.box_url = "http://mathlab.utsc.utoronto.ca/courses/cscd27f16/assignment/02/boxes/trusty64_minimal.box"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 55555, host: 55555
  config.vm.provision "shell", path: "setup.sh"
  config.vm.provider 'virtualbox' do |v|
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--audio", "none", "--usb", "on", "--usbehci", "off"]
  end
end

