# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "minimal/trusty64"
  config.vm.box_url = "http://mathlab.utsc.utoronto.ca/courses/cscd27f16/assignment/02/boxes/trusty64_minimal.box"
  config.vm.network "forwarded_port", guest: 11111, host: 11111
  config.vm.network "forwarded_port", guest: 55555, host: 55555
  config.vm.provision "shell", inline: "sudo apt-get update"
  config.vm.provision "shell", inline: "sudo DEBIAN_FRONTEND=noninteractive apt-get install gdb gcc-multilib libssl-dev -y"
  config.vm.provision "shell", run: "always", inline: "echo 0 | sudo tee /proc/sys/kernel/randomize_va_space"
  config.vm.provider 'virtualbox' do |v|
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--audio", "none", "--usb", "on", "--usbehci", "off"]
  end
end

